export {
  TtsApiError,
  cancelTtsJob,
  fetchTtsConfig,
  fetchTtsVoices,
  generateChapterAudio,
  generateNarrationPlan,
  getChapterAudio,
  getChapterAudioDownloadUrl,
  getNarrationPlan,
  getTtsJob,
  retryTtsJob,
  saveNarrationPlan,
  synthesizeSpeech,
  type MossLocalAdvancedOptions,
  type TtsAdvancedOptions,
  type TtsCacheState,
  type TtsChapterAudioManifest,
  type TtsChapterAudioSegment,
  type TtsChapterGenerateResponse,
  type TtsChapterRequestOptions,
  type TtsConfig,
  type TtsErrorCode,
  type TtsJob,
  type TtsJobProgress,
  type TtsJobStatus,
  type TtsNarrationMode,
  type TtsNarrationPlan,
  type TtsNarrationPlanRequestOptions,
  type TtsNarrationSegment,
  type TtsNarrationSpeaker,
  type TtsProvider,
  type TtsProviderCapabilities,
  type TtsProviderConfig,
  type TtsProviderError,
  type TtsProviderStatus,
  type TtsRoleVoice,
  type TtsSpeakerVoiceMapping,
  type TtsSynthesizeOptions,
  type TtsVoiceInfo,
} from './api';
export {
  canExportManifestInBrowser,
  canUseBrowserFfmpegExport,
  exportChapterMp3InBrowser,
  type BrowserMp3ExportResult,
} from './browserFfmpegExport';
export {
  chunkNativeSpeechText,
  getNativeVoices,
  isNativeSpeechSupported,
  type NativeTtsVoice,
} from './nativeSpeech';
export { useTts, type TtsPlaybackEngine, type UseTtsOptions, type TtsState } from './hooks';
